# Generated by Django 2.0.1 on 2018-01-10 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Entry'),
        ),
    ]
