# Generated by Django 2.0.1 on 2018-01-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20180110_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateField(verbose_name='%m/%d/%Y'),
        ),
    ]
