# Generated by Django 2.0.1 on 2018-01-31 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_entry_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateField(unique_for_date='pub_Date', verbose_name='%m/%d/%Y'),
        ),
    ]
