# Generated by Django 2.0.1 on 2018-01-31 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_auto_20180130_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateField(unique=True, verbose_name='%m/%d/%Y'),
        ),
    ]
