# Generated by Django 2.0.1 on 2018-01-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_auto_20180130_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='summary',
            field=models.TextField(blank=True, default='You have not written a summary for today yet.'),
        ),
    ]
