# Generated by Django 2.0.1 on 2018-03-18 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_auto_20180131_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='%m/%d/%Y')),
                ('venue', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(default='You have written no notes about this concert.')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='concert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Concert'),
        ),
    ]
