# Generated by Django 2.0.1 on 2018-04-15 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_auto_20180414_1910'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artist',
            table='artist',
        ),
    ]
