# Generated by Django 2.0.1 on 2018-04-15 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0016_auto_20180414_1912'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artist',
            table='artist',
        ),
    ]
