# Generated by Django 2.0.1 on 2018-04-15 03:36

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('journal', '0018_auto_20180414_1930'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activity',
            table='activity',
        ),
        migrations.AlterModelTable(
            name='concert',
            table='concert',
        ),
        migrations.AlterModelTable(
            name='entry',
            table='entry',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='venue',
            table='venue',
        ),
    ]
