# Generated by Django 2.0.1 on 2018-04-15 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0020_auto_20180414_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='journal.Venue'),
        ),
    ]
