# Generated by Django 2.0.1 on 2018-04-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0021_auto_20180415_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.SmallIntegerField(default=0),
        ),
    ]
