# Generated by Django 2.0.1 on 2018-04-24 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0022_activity_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity_name',
            new_name='name',
        ),
    ]
